Vagrant.configure(2) do |config|

  # Use caches
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  config.vm.define "node1", primary: true do |node1|
    node1.vm.box = "ubuntu/trusty64"
    node1.vm.hostname = "vagrant-devstack-node-1"
    node1.vm.network "private_network", ip: "10.0.0.3"
  end

  config.vm.define "node2" do |node2|
    node2.vm.box = "ubuntu/trusty64"
    node2.vm.hostname = "vagrant-devstack-node-2"
    node2.vm.network "private_network", ip: "10.0.0.4"
    config.vm.provision "shell", privileged:false,
      inline: "sed -i 's/10.0.0.3/10.0.0.4/' ~/devstack/local.conf"
  end

  config.vm.provider :virtualbox do |v|
    v.customize ["modifyvm", :id, "--memory", 2048]
    v.customize ["modifyvm", :id, "--cpus", 8]
  end
  
  config.vm.provision "shell",
      inline: "apt-get update"

  config.vm.provision "shell",
      inline: "apt-get install -y git"

  config.vm.provision "shell", privileged:false,
    inline: "git clone ~/openstack-dev/devstack /home/vagrant/devstack"

  config.vm.provision "shell", privileged:false,
    inline: "cp /vagrant/local.conf ~/devstack/"

  config.vm.synced_folder("~/src/openstack", "/home/vagrant/openstack", id:"v-openstack-src", create: true)
   config.vm.synced_folder("~/src/openstack-dev", "/home/vagrant/openstack-dev", id:"v-openstack-dev", create: true)
end
